name: Build y Deploy Autom谩tico

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: 1. Obtener c贸digo
      uses: actions/checkout@v4

    - name: 2. Configurar Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: 'npm' # Ayuda a que las instalaciones sean m谩s r谩pidas y fiables

    - name: 3. Instalar dependencias
      # Usamos ci para una instalaci贸n limpia y exacta seg煤n tu package-lock.json
      run: npm install 

    - name: 4. Compilar proyecto
      # Usamos npx para forzar la ejecuci贸n del vite local instalado
      run: npx vite build

    - name: 5.  Subir SOLO la compilaci贸n a Hostinger
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ${{ secrets.FTPSERVER }}
        username: ${{ secrets.FTPUSER }}
        password: ${{ secrets.FTPPASS }}
        local-dir: ./dist/
        server-dir: ./
