name: Build Production para Hostinger

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout del c√≥digo
      uses: actions/checkout@v4

    - name: Configurar Node.js 24
      uses: actions/setup-node@v4
      with:
        node-version: 24

    - name: Instalar dependencias
      run: npm install

    - name: Instalar vite
      run: npm install -D vite @vitejs/plugin-react

    - name: Compilar
      run: npm run build

    - name: Guardar Web Terminada (Artifact)
      uses: actions/upload-artifact@v4
      with:
        name: proyecto-cocinas-final
        path: dist/
